strategy:
  fail-fast: true
  matrix:
    os: [ubuntu-latest]
    php: [8.1, 8.2]
    laravel: [10.*]
    include:
      - laravel: 10.*
        testbench: 8.*
      - laravel: 9.*
        testbench: 7.*
    exclude:
      - php: 8.2
        laravel: 9.*
    node-version: [16, 18, 20]

name: run-tests

jobs:
  test:
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
      - name: Execute tests
        run: vendor/bin/phpunit
